# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Colorado Data Science Team
email: p.rodriguez@colorado.edu
description: > # this means to ignore newlines until "baseurl:"
  Colorado Data Science Team (CoData)
baseurl: "" # the subpath of your site, e.g. /blog
url: "codatascience.github.io" # the base hostname & protocol for your site
github_username: CoDataScience

# Build settings
markdown: kramdown
include: ['slides']
exclude: ['LICENSE', 'README.md', 'Gemfile', 'Gemfile.lock']
permalink: '/:year/:month/:day/:title.html'

collections:
  notebooks:
    output: true
    permalink: /notebooks/:path/


# Gems
gems: [jekyll-paginate]
paginate: 2
paginate_path: '/blog/page:num/'
